// This file is @generated by prost-build.
/// stringified payload linked to -> (string params) in WsData
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WsParamsPayload {
    #[prost(string, tag = "1")]
    pub market_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub yes_price: f64,
    #[prost(double, tag = "3")]
    pub no_price: f64,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BitcoinPricePayload {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// ✅ Add market ID
    #[prost(string, tag = "2")]
    pub market_id: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub current_price: f64,
    #[prost(double, tag = "4")]
    pub target_price: f64,
    #[prost(int64, tag = "5")]
    pub target_timestamp: i64,
    #[prost(uint64, tag = "6")]
    pub seconds_remaining: u64,
    #[prost(bool, tag = "7")]
    pub is_above_target: bool,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
    #[prost(double, tag = "9")]
    pub price_difference: f64,
    #[prost(double, tag = "10")]
    pub percent_to_target: f64,
    #[prost(bool, tag = "11")]
    pub less_than_40_secs: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketMessage {
    #[prost(oneof = "market_message::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<market_message::Payload>,
}
/// Nested message and enum types in `MarketMessage`.
pub mod market_message {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Price(super::BitcoinPricePayload),
        #[prost(message, tag = "2")]
        Params(super::WsParamsPayload),
    }
}
